### ISSUE TITLE
I seem to found a small bug in your FTT-NAS project...

### ISSUE THREAD

**Issue by BaronNashorMan** [walkerning/aw_nas#41]
First of all, thank you for taking the time to modify your FTT-NAS guidance document.
After you modify the FTT-NAS README, I proceeded step by step according to your instructions, but in the end there was an error like the previous question, which is stuck at
`aw_nas/aw_nas/objective/fault_injection.py  159 line  np.random.randint(0, 2 * _n_err,size=size_)`

I think the problem should appear aw_nas/aw_nas/objective/fault_injection.py on line 152：
`size_ = fault_ind.sum().cpu().data`

The size parameter in np.random.randint does not seem to support Tensor type variables，It only supports int or tuple... So I tried the following to modify your code:
`size_ = fault_ind.sum().cpu().data --> size_ = fault_ind.sum().cpu().numpy()`

After my attempts to modify, this BUG seems to disappear, and now the project can work normally.
**So, if you have time, please confirm whether this bug appears when FTT-NAS uses GPU to search, and whether my solution is appropriate, thank you very much!**

**Comment by walkerning** [comment]
![image](https://user-images.githubusercontent.com/4240346/91861695-b17dfa80-ec9f-11ea-8778-a5779f9eaca8.png)
Hi, many thanks for your information! What's the numpy and pytorch version in your env? Because it's weird that I can successfully run the search.

**Comment by BaronNashorMan** [comment]
Thanks again for your patient reply. My numpy and Pytorch versions are 1.19.1 and 1.1.0  in my env.
![image](https://user-images.githubusercontent.com/40259853/91872058-06bf0980-ecaa-11ea-9b0e-1ded6ec0ab36.png)

Maybe there is something wrong with my numpy version.  Because the version you requested is 1.16.3 .
I will try to modify it. Thank you for your answer.

**Comment by walkerning** [comment]
As a reference, here are some lib versions in my env:
![image](https://user-images.githubusercontent.com/4240346/91935759-044bc680-ed21-11ea-9bdb-02eb91880ac7.png)

**Comment by BaronNashorMan** [comment]
Hi, thank you. It is indeed a problem with the numpy version in my environment. According to your instructions, the problem has now been solved and I can start the search task normally.
I hope the following steps can successfully complete your entire FTT-NAS mission. Thank you very much!
