### ISSUE TITLE
In aw_nas/aw_nas/objective/zerocost.py, the module foresight cannot be imported.

### ISSUE THREAD

**Issue by 96jhwei** [walkerning/aw_nas#58]
In aw_nas/aw_nas/objective/zerocost.py, the module foresight cannot be imported.

The corresponding .py file also cannot be found.

How to address this??

**Comment by walkerning** [comment]
Hey, you can clone this repo https://github.com/zhouzx17/zero-cost-nas, and add its path to your $PYTHONPATH env variable.

**Comment by walkerning** [comment]
Hope the above solution has solved your problem. If you have any other problems, feel free to open another issue.
