### ISSUE TITLE
How to change the environment variable “AWNAS_HOME“

### ISSUE THREAD

**Issue by 809253928** [walkerning/aw_nas#59]
AWNAS_HOME is an environment variable default to be ~/awnas. How to specialize this？

Thank you！

**Comment by walkerning** [comment]
Hi, you can set `AWNAS_HOME` as any other usual environment variables. 
* For example, by running `export AWNAS_HOME=/the/path/to/your/desired/dir` in a shell, this environment variable will be inherited by all subsequent processes spawned by this shell session.
* Or if you just want to specify it for one `awnas` run, you can  add it before the `awnas` command, like `AWNAS_HOME=/the/path/to/your/desired/dir awnas search --gpu 0 --train-dir ......` (See https://github.com/walkerning/aw_nas/blob/master/examples/research/ftt-nas/run_mibb_search.sh#L30 for an example)

**Comment by walkerning** [comment]
Hope that've solved your question. If you have any further questions, feel free to open new issues!
