### ISSUE TITLE
Code for TA-GATES

### ISSUE THREAD

**Issue by akhauriyash** [walkerning/aw_nas#69]
Hello,

I hope I am not missing something, but I cannot find the code/documentation for the TA-GATES paper. (https://openreview.net/forum?id=74fJwNrBlPI)

Has it been released yet? If not, when is the planned release?

**Comment by 5thGenDev** [comment]
found gates but not ta-gates

**Comment by nam-drun** [comment]
> Hello,
> 
> I hope I am not missing something, but I cannot find the code/documentation for the TA-GATES paper. (https://openreview.net/forum?id=74fJwNrBlPI)
> 
> Has it been released yet? If not, when is the planned release?

tagates is now av

**Comment by walkerning** [comment]
Sorry that we don't receive any notifications on this issue... But fortunately you found the code.
